security:
  # Configuration des hasheurs de mot de passe
  password_hashers:
    App\Entity\User:
      algorithm: bcrypt
      encode_as_base64: false
      iterations: 1

  # Configuration du fournisseur d'utilisateur
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  # Configuration des pare-feu
  firewalls:
    login:
      pattern: ^/api/login
      stateless: true
      provider: app_user_provider
      json_login:
        username_path: email
        check_path: /api/login_check
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure

    api:
      pattern: ^/api
      stateless: true
      jwt: ~

    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

  # Configuration des contrôles d'accès
  access_control:
    # - { path: ^/admin, roles: ROLE_ADMIN }
    # - { path: ^/profile, roles: ROLE_USER }
