<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXoSNqaV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXoSNqaV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXoSNqaV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXoSNqaV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXoSNqaV\App_KernelDevDebugContainer([
    'container.build_hash' => 'XoSNqaV',
    'container.build_id' => 'b2f7f895',
    'container.build_time' => 1711706285,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXoSNqaV');
