<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJxGqPpP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJxGqPpP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJxGqPpP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJxGqPpP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJxGqPpP\App_KernelDevDebugContainer([
    'container.build_hash' => 'JxGqPpP',
    'container.build_id' => '688c648d',
    'container.build_time' => 1714564680,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJxGqPpP');
