<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCVuE3t8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCVuE3t8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCVuE3t8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCVuE3t8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCVuE3t8\App_KernelDevDebugContainer([
    'container.build_hash' => 'CVuE3t8',
    'container.build_id' => 'd6308f8f',
    'container.build_time' => 1711620060,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCVuE3t8');
