<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\LoginController::index'], [], [['text', '/login']], [], [], []],
    'app_login_post' => [[], ['_controller' => 'App\\Controller\\LoginController::login'], [], [['text', '/login']], [], [], []],
    'song_index' => [[], ['_controller' => 'App\\Controller\\SongController::index'], [], [['text', '/songs']], [], [], []],
    'song_show' => [['id'], ['_controller' => 'App\\Controller\\SongController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/songs']], [], [], []],
    'song_new' => [[], ['_controller' => 'App\\Controller\\SongController::new'], [], [['text', '/songs']], [], [], []],
    'song_edit' => [['id'], ['_controller' => 'App\\Controller\\SongController::edit'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/songs']], [], [], []],
    'song_delete' => [['id'], ['_controller' => 'App\\Controller\\SongController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/songs']], [], [], []],
    'App\Controller\LoginController::index' => [[], ['_controller' => 'App\\Controller\\LoginController::index'], [], [['text', '/login']], [], [], []],
    'App\Controller\LoginController::login' => [[], ['_controller' => 'App\\Controller\\LoginController::login'], [], [['text', '/login']], [], [], []],
    'App\Controller\SongController::index' => [[], ['_controller' => 'App\\Controller\\SongController::index'], [], [['text', '/songs']], [], [], []],
    'App\Controller\SongController::show' => [['id'], ['_controller' => 'App\\Controller\\SongController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/songs']], [], [], []],
    'App\Controller\SongController::new' => [[], ['_controller' => 'App\\Controller\\SongController::new'], [], [['text', '/songs']], [], [], []],
    'App\Controller\SongController::edit' => [['id'], ['_controller' => 'App\\Controller\\SongController::edit'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/songs']], [], [], []],
    'App\Controller\SongController::delete' => [['id'], ['_controller' => 'App\\Controller\\SongController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/songs']], [], [], []],
];
